### ISSUE TITLE
Investigate AT failures on K8s

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-acceptance-tests#10]
Failures are on 2.1 actuator endpoints, in particular, the `/log` endpoint is secured by default.

**Comment by sobychacko** [comment]
Resolved through https://github.com/spring-cloud/spring-cloud-stream-acceptance-tests/commit/c737d3231db0466e7214de48f983dd6acb40df87 and https://github.com/spring-cloud/spring-cloud-stream-acceptance-tests/commit/90c5b811de50982414eb94ad6c1f3e9ea32acdf2.
