### ISSUE TITLE
Cleanup LB and other unused resources after test runs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-acceptance-tests#7]

**Comment by sabbyanandan** [comment]
See: https://jenkins.spring.io/view/SpringCloudStream/view/CI/job/spring-cloud-stream-k8s-acceptance-tests-master-ci/

**Comment by sobychacko** [comment]
Closing this issue in favor of https://github.com/spring-cloud/spring-cloud-stream-acceptance-tests/issues/8.
